services:
  frontend:
    container_name: frontend
    build: ./
    ports:
      - "4173:4173"
    networks:
      - sad_network
      - supabase_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`sad.khesir.com`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=4173"

networks:
  sad-app:
    external: true
  supabase_network:
    external: true
    name: supabase_network_Backend-Enterprise-Management-System
